### ISSUE TITLE
Better removing `plugin` from the plugin name and the folder name

### ISSUE THREAD

**Issue by pcav** [jsalcal/rasor-plugin#3]
Although it does not hurt, I think this is pleonastic, it is inconsistent and thus it may be slightly confusing for users

**Comment by jsalcal** [comment]
I have to disagree on this one. For example, the openlayers_plugin is also named this way.

**Comment by pcav** [comment]
Yes, many are named this way. We are slowly bringing all on the same standard, so the more natural way is starting with the new ones, where the impact is minimal.
